version: '3.8'

services:
  ocr-engine:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 4G
    restart: unless-stopped
    environment:
      - PORT=8080
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - TRANSFORMERS_CACHE=/app/.cache/huggingface
      - HF_HOME=/app/.cache/huggingface
      - TORCH_HOME=/app/.cache/torch
      - HF_HUB_DISABLE_SYMLINKS_WARNING=1
      - HF_HUB_OFFLINE=0
    volumes:
      # Mount test bills for testing
      - ./test_bills:/app/test_bills:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 300s