# Nixpacks configuration for OCR Engine deployment

[phases.setup]
nixPkgs = ["python310", "gcc", "git", "wget", "glib", "xorg.libSM", "xorg.libXext", "xorg.libXrender"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r api/requirements.txt"
]

[phases.build]
cmds = [
    # Create necessary directories
    "mkdir -p /app/.cache/huggingface",
    "mkdir -p /tmp/surya_ocr_api"
]

[start]
cmd = "uvicorn api.main:app --host 0.0.0.0 --port ${PORT:-8080}"

[variables]
PYTHONUNBUFFERED = "1"
TRANSFORMERS_CACHE = "/app/.cache/huggingface"
HF_HOME = "/app/.cache/huggingface"