# Nixpacks configuration for OCR Engine deployment

[phases.setup]
# Include all necessary system packages for OCR, image processing, and OpenCV
nixPkgs = [
    "python310", 
    "gcc", 
    "g++", 
    "git", 
    "wget",
    "pkg-config",
    # OpenCV dependencies
    "opencv",
    "glib",
    "libglvnd",
    "xorg.libSM", 
    "xorg.libXext", 
    "xorg.libXrender",
    "xorg.libICE",
    "xorg.libX11",
    # Additional libraries
    "libgthread-2.0", 
    "libgomp", 
    "libquadmath",
    "zlib",
    "libjpeg",
    "libpng",
    "libtiff",
    "libwebp"
]

[phases.install]
cmds = [
    "pip install --upgrade pip setuptools wheel",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    # Debug environment
    "echo '=== Railway Build Environment ==='",
    "pwd",
    "ls -la",
    "echo '=== Python Environment ==='",
    "python --version",
    "pip --version",
    "echo '=== Installed Packages ==='",
    "pip list | grep -E '(surya|opencv|transformers|torch|qwen)' || echo 'No matching packages found'",
    "echo '=== Surya Package Details ==='",
    "pip show surya-ocr || echo 'surya-ocr not found'",
    "echo '=== Python Path ==='",
    "python -c 'import sys; print(\"\\n\".join(sys.path))'",
    "echo '=== Project Structure ==='",
    "find . -name '*.py' -type f | head -20",
    "echo '=== Checking imports ==='",
    "python -c 'import sys; sys.path.insert(0, \".\"); import api.main' || echo 'Failed to import api.main'",
    # Create necessary directories
    "mkdir -p .cache/huggingface",
    "mkdir -p .cache/torch",
    "mkdir -p /tmp/surya_ocr_api",
    # Ensure proper permissions
    "chmod -R 777 /tmp/surya_ocr_api"
]

[start]
# Use current directory with PYTHONPATH
cmd = "PYTHONPATH=. python -m uvicorn api.main:app --host 0.0.0.0 --port ${PORT:-8080}"

[variables]
# Python environment
PYTHONUNBUFFERED = "1"
PYTHONPATH = "."
# Model caching directories (use relative paths)
TRANSFORMERS_CACHE = ".cache/huggingface"
HF_HOME = ".cache/huggingface"
TORCH_HOME = ".cache/torch"
# Hugging Face settings
HF_HUB_DISABLE_SYMLINKS_WARNING = "1"
HF_HUB_OFFLINE = "0"
# OpenCV settings
OPENCV_IO_ENABLE_OPENEXR = "1"