# Railway deployment configuration

[build]
builder = "NIXPACKS"

[deploy]
runtime = "V2"
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "uvicorn api.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300

[deploy.multiRegionConfig."europe-west4-drams3a"]
numReplicas = 1

[env]
PYTHONUNBUFFERED = "1"
TRANSFORMERS_CACHE = "/app/.cache/huggingface"
HF_HOME = "/app/.cache/huggingface"
# Increase timeout for model loading
UVICORN_TIMEOUT_KEEP_ALIVE = "120"

# Railway-specific settings
[[services]]
name = "ocr-engine"
region = "us-west"
plan = "hobby"

# Resource limits
[services.resources]
memory = "2Gi"
cpu = "1"

# Scaling configuration
[services.scaling]
minInstances = 1
maxInstances = 3

# Custom domains (optional)
# [[services.domains]]
# domain = "ocr-api.yourdomain.com"