# Railway deployment configuration

[build]
builder = "NIXPACKS"

[deploy]
runtime = "V2"
numReplicas = 1
sleepApplication = false
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
startCommand = "python -m uvicorn api.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 600  # 10 minutes for model download

[deploy.multiRegionConfig."europe-west4-drams3a"]
numReplicas = 1

[env]
PYTHONUNBUFFERED = "1"
TRANSFORMERS_CACHE = "/app/.cache/huggingface"
HF_HOME = "/app/.cache/huggingface"
UVICORN_TIMEOUT_KEEP_ALIVE = "120"