# Railway deployment configuration

[build]
builder = "NIXPACKS"

[deploy]
runtime = "V2"
numReplicas = 1
sleepApplication = false
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
startCommand = "sh -c 'python -m uvicorn api.main:app --host 0.0.0.0 --port ${PORT:-8080}'"
healthcheckPath = "/health"
healthcheckTimeout = 600  # 10 minutes for model download

[deploy.multiRegionConfig."europe-west4-drams3a"]
numReplicas = 1

[env]
PYTHONUNBUFFERED = "1"
TRANSFORMERS_CACHE = "/app/.cache/huggingface"
HF_HOME = "/app/.cache/huggingface"
TORCH_HOME = "/app/.cache/torch"
HF_HUB_DISABLE_SYMLINKS_WARNING = "1"
HF_HUB_OFFLINE = "0"
UVICORN_TIMEOUT_KEEP_ALIVE = "120"
# Increase timeout for model loading
UVICORN_TIMEOUT_GRACEFUL_SHUTDOWN = "120"